import { useEffect, useState } from "react";
import { useAuth, useUser } from "@clerk/clerk-react";
import { Heart } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import axios from "axios";
import toast from "react-hot-toast";
import { useTheme } from "@/context/ThemeContext";

axios.defaults.baseURL = import.meta.env.VITE_BASE_URL;

const Community = () => {
  const [creations, setCreations] = useState([]);
  const { user } = useUser();
  const { getToken } = useAuth();
  const { theme } = useTheme();
  const [loading, setLoading] = useState(true);

  const isDark = theme === "dark";

  const fetchCreations = async () => {
    try {
      const { data } = await axios.get(
        "/api/user/get-published-creations",
        { headers: { Authorization: `Bearer ${await getToken()}` } }
      );

      data.success ? setCreations(data.creations) : toast.error(data.message);
    } catch (error) {
      toast.error(error.message);
    }
    setLoading(false);
  };

  const imageLikeToggle = async (id) => {
    try {
      const { data } = await axios.post(
        "/api/user/toggle-like-creation",
        { id },
        { headers: { Authorization: `Bearer ${await getToken()}` } }
      );

      if (data.success) {
        toast.success(data.message);
        fetchCreations();
      } else {
        toast.error(data.message);
      }
    } catch (error) {
      toast.error(error.message);
    }
  };

  useEffect(() => {
    if (user) fetchCreations();
  }, [user]);

  if (loading) {
    return (
      <div
        className={`flex items-center justify-center min-h-[calc(100vh-64px)]
        ${isDark ? "bg-zinc-950" : "bg-gray-50"}`}
      >
        <span className="w-10 h-10 rounded-full border-4 border-zinc-400 border-t-transparent animate-spin" />
      </div>
    );
  }

  return (
    <section
      className={`min-h-[calc(100vh-64px)] px-4 sm:px-6 lg:px-10 py-10 transition-colors
      ${isDark ? "bg-zinc-950 text-zinc-100" : "bg-gray-50 text-zinc-900"}`}
    >
      {/* Header */}
      <div className="max-w-7xl mx-auto mb-8 text-center">
        <h2 className="text-2xl font-semibold tracking-tight">
          Community Creations
        </h2>
        <p className="text-sm text-zinc-500 mt-1">
          Explore images generated by the community
        </p>
      </div>

      {/* Grid */}
      <div className="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {creations.map((creation, index) => (
          <Card
            key={index}
            className={`group relative overflow-hidden rounded-2xl border shadow-lg transition
            ${
              isDark
                ? "bg-zinc-900/70 border-zinc-800 hover:shadow-2xl"
                : "bg-white border-gray-200 hover:shadow-xl"
            }`}
          >
            <CardContent className="p-0">
              {/* Image */}
              <img
                src={creation.content}
                alt={creation.prompt}
                className="h-64 w-full object-cover transition-transform duration-300 group-hover:scale-105"
              />

              {/* Overlay */}
              <div
                className={`absolute inset-0 flex flex-col justify-end opacity-0 group-hover:opacity-100 transition-opacity
                ${
                  isDark
                    ? "bg-gradient-to-t from-zinc-950/90 via-zinc-950/40"
                    : "bg-gradient-to-t from-white/90 via-white/40"
                }`}
              >
                <div className="p-4 flex items-center justify-between gap-3">
                  <p className="text-xs truncate max-w-[75%]">
                    {creation.prompt}
                  </p>

                  <div className="flex items-center gap-1.5">
                    <span className="text-xs">
                      {creation.likes.length}
                    </span>
                    <Heart
                      onClick={() => imageLikeToggle(creation.id)}
                      className={`w-5 h-5 cursor-pointer transition-transform hover:scale-110
                        ${
                          creation.likes.includes(user?.id)
                            ? "fill-red-500 text-red-500"
                            : "text-zinc-400 hover:text-red-400"
                        }`}
                    />
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  );
};

export default Community;
